### ISSUE TITLE
Refresh to `1.0.3` snap release causes regression, crashing the service when connecting to controllers

### ISSUE THREAD

**Issue by johnlettman** [canonical/prometheus-juju-exporter#51] opened 2023-05-12 20:55 UTC
Hello,

We have encountered a regression on snap release `1.0.3` where attempts to connect to the Juju controllers fail due to an incompatibility. This issue has arisen from a variety of customer sites as soon as the refresh occurs from `1.0.2` to `1.0.3`. 

The following controllers are impacted: 
- Juju version 2.7.6 on bionic
- Juju version 2.8.8 on bionic
- Juju version 2.8.4 on bionic

The following is a log sample from the failure:
```
May 12 20:28:52 juju-3 systemd[1]: Started Service for snap application prometheus-juju-exporter.prometheus-juju-exporter.
May 12 20:28:53 juju-3 prometheus-juju-exporter.prometheus-juju-exporter[29632]: 2023-05-12 20:28:53,629 INFO - Configuration parsed successfully
May 12 20:28:53 juju-3 prometheus-juju-exporter.prometheus-juju-exporter[29632]: 2023-05-12 20:28:53,629 INFO - Parsed config: /var/snap/prometheus-juju-exporter/44
May 12 20:28:53 juju-3 prometheus-juju-exporter.prometheus-juju-exporter[29632]: 2023-05-12 20:28:53,629 INFO - Configuration parsed successfully
May 12 20:28:53 juju-3 prometheus-juju-exporter.prometheus-juju-exporter[29632]: 2023-05-12 20:28:53,629 DEBUG - Collector initialized
May 12 20:28:53 juju-3 prometheus-juju-exporter.prometheus-juju-exporter[29632]: 2023-05-12 20:28:53,629 DEBUG - Exporter initialized
May 12 20:28:53 juju-3 prometheus-juju-exporter.prometheus-juju-exporter[29632]: 2023-05-12 20:28:53,630 DEBUG - Running prometheus client http server.
May 12 20:28:53 juju-3 prometheus-juju-exporter.prometheus-juju-exporter[29632]: 2023-05-12 20:28:53,631 INFO - Collecting gauges...
May 12 20:28:53 juju-3 prometheus-juju-exporter.prometheus-juju-exporter[29632]: 2023-05-12 20:28:53,631 INFO - Connecting to controller at [REDACTED]:17070
May 12 20:28:53 juju-3 prometheus-juju-exporter.prometheus-juju-exporter[29632]: 2023-05-12 20:28:53,744 WARNING - Failed to connect to Juju controller at [REDACTED]:17070: juju server-version 2.7.6 not supported
May 12 20:28:54 juju-3 prometheus-juju-exporter.prometheus-juju-exporter[29632]: 2023-05-12 20:28:54,748 ERROR - Collection job resulted in error: Unable to connect to any of the Juju controllers.
May 12 20:28:54 juju-3 systemd[1]: snap.prometheus-juju-exporter.prometheus-juju-exporter.service: Main process exited, code=exited, status=1/FAILURE
May 12 20:28:54 juju-3 systemd[1]: snap.prometheus-juju-exporter.prometheus-juju-exporter.service: Failed with result 'exit-code'.
```

**Comment by agileshaw** [comment] 2023-05-12 22:38
The libjuju package dependency has reverted, hence the issue is temporarily resolved. However, a more sophisticated and sustainable solution is needed to address the juju version issue.

**Comment by agileshaw** [comment] 2023-07-14 13:05
Closing the issue because the implementation of snap versioning is completed.

**Closed by agileshaw** 2023-07-14 13:05 UTC
Labels: bug, BSENG-1189
